#!/usr/bin/env bash
set -e

# Get boot partition
UUID_LINE=$(grep '@boot_linux' /etc/fstab)
UUID=$(sed -n 's/.*UUID=\([^ ]*\).*/\1/p' <<< $UUID_LINE)
BOOT_DEVICE=$(findfs UUID=$UUID)
sed -i '/ROOT=/a BOOT_DEVICE='$DEVICE'' /etc/calamares/scripts/deploy_to_common

# Get root partition
UUID_LINE=$(grep '@_linux' /etc/fstab)
UUID=$(sed -n 's/.*UUID=\([^ ]*\).*/\1/p' <<< $UUID_LINE)
DEVICE=$(findfs UUID=$UUID)
sed -i '/BOOT_DEVICE=/a DEVICE='$DEVICE'' /etc/calamares/scripts/deploy_to_common

# Change fstab
sed -i '0,/@_linux/ s|@_linux|@.snapshots_linux/rootfs/snapshot-deploy|' /etc/fstab
sed -i '0,/@etc_linux/ s|@etc_linux|@.snapshots_linux/etc/etc-deploy|' /etc/fstab
sed -i '0,/@var_linux/ s|@var_linux|@.snapshots_linux/var/var-deploy|' /etc/fstab
echo '/.snapshots/ash/root /root none bind 0 0' >> /etc/fstab
echo '/.snapshots/ash/tmp /tmp none bind 0 0' >> /etc/fstab

# Grub update
sed -i 's/\bLinux\b//g; s/  */ /g' /boot/grub/grub.cfg
sed -i '0,/@boot_linux/vmlinuz-linux s|/@boot_linux/vmlinuz-linux|/@.snapshots_linux/rootfs/snapshot-deploy/boot/vmlinuz-linux|' /boot/grub/grub.cfg
sed -i '0,/@boot_linux/initramfs-linux.img s|/@boot_linux/initramfs-linux.img|/@.snapshots_linux/rootfs/snapshot-deploy/boot/initramfs-linux.img|' /boot/grub/grub.cfg
