#!/usr/bin/env bash
set -e

# Change fstab
sed -i '0,/@_linux/ s|@_linux|@.snapshots_linux/rootfs/snapshot-deploy|' /etc/fstab
sed -i '0,/@boot_linux/ s|@boot_linux|@.snapshots_linux/boot/boot-deploy|' /etc/fstab
sed -i '0,/@etc_linux/ s|@etc_linux|@.snapshots_linux/etc/etc-deploy|' /etc/fstab
sed -i '0,/@var_linux/ s|@var_linux|@.snapshots_linux/var/var-deploy|' /etc/fstab
echo '/.snapshots/ash/root /root none bind 0 0' >> /etc/fstab
echo '/.snapshots/ash/tmp /tmp none bind 0 0' >> /etc/fstab

# Grub update
awk -i inplace '/@boot_linux/ && /vmlinuz-linux/ { gsub(/@boot_linux\/vmlinuz-linux/, "@.snapshots_linux/rootfs/snapshot-deploy/boot/vmlinuz-linux") } 1' /boot/grub/grub.cfg
awk -i inplace '/@boot_linux/ && /initramfs-linux.img/ { gsub(/@boot_linux\/initramfs-linux.img/, "@.snapshots_linux/rootfs/snapshot-deploy/boot/initramfs-linux.img") } 1' /boot/grub/grub.cfg
