#!/usr/bin/env bash
set -e
ROOT="$1"

# Unmount mount points
umount -lv ${ROOT}/boot
umount -lv ${ROOT}/etc
umount -lv ${ROOT}/var

# Mount boot subvolume
mount "${BOOT_DEVICE}" -t btrfs -o "subvol=@boot_linux,compress=zstd,noatime" ${ROOT}/.snapshots/boot/boot-deploy
cp -r --reflink=auto ${ROOT}/.snapshots/boot/boot-deploy/* ${ROOT}/boot/

# Mount etc subvolume
mount "${ROOT}" -t btrfs -o "subvol=@etc_linux,compress=zstd,noatime" ${ROOT}/.snapshots/etc/etc-deploy
cp -r --reflink=auto ${ROOT}/.snapshots/etc/etc-deploy/* ${ROOT}/etc/

# Mount var subvolume
mount "${ROOT}" -t btrfs -o "subvol=@var_linux,compress=zstd,noatime" ${ROOT}/.snapshots/var/var-deploy
cp -r --reflink=auto ${ROOT}/.snapshots/var/var-deploy/* ${ROOT}/var/

# Copy base snapshots into deploy root
cp -r --reflink=auto ${ROOT}/.snapshots/boot/boot-0/* ${ROOT}/.snapshots/rootfs/snapshot-deploy/boot/
cp -r --reflink=auto ${ROOT}/.snapshots/etc/etc-0/* ${ROOT}/.snapshots/rootfs/snapshot-deploy/etc/
cp -r --reflink=auto ${ROOT}/.snapshots/var/var-0/* ${ROOT}/.snapshots/rootfs/snapshot-deploy/var/
