#!/usr/bin/env bash
set -e
ROOT="$1"

# Get the device mounted at the root partition
DEVICE=$(findmnt -n -v -o SOURCE ${ROOT})

# Get the UUID of that device
UUID=$(blkid -s UUID -o value "$DEVICE")

echo $UUID > ${ROOT}/.snapshots/ash/part
