# SPDX-FileCopyrightText: no
# SPDX-License-Identifier: CC0-1.0
---
iconPath: "/usr/share/calamares/modules/distribution/icons"
packages:
    KDE-Desktop:
        arch: [ plasma-desktop, sddm, sddm-kcm, plasma-nm, plasma-pa, dolphin, konsole, kdeplasma-addons, kde-gtk-config, breeze-gtk, kscreen, spectacle, powerdevil, ark, gwenview, mpv, kate, flatpak, discover, firefox ]
        debian: [ task-kde-desktop, sddm, sddm-kcm ]
        fedora: [ "@KDE Plasma Desktop", sddm ]
    GNOME-Desktop:
        arch: [ gnome, flatpak ]
        debian: [ task-gnome-desktop, flatpak ]
        fedora: [ "@GNOME Desktop", flatpak ]
    Xfce4:
        arch: [ xfce4, xfce4-goodies, cosmic-store, lightdm-gtk-greeter, firefox, vlc ]
        debian: [ task-xfce-desktop, lightdm-gtk-greeter ]
        fedora: [ "@Xfce Desktop", lightdm-gtk-greeter ]
    Budgie-Desktop:
        arch: [ budgie, firefox, cosmic-store, lightdm-gtk-greeter, gnome-terminal, vlc ]
        debian: [ budgie-desktop, lightdm-gtk-greeter ]
        fedora: [ budgie-desktop, lightdm-gtk-greeter ]
    Cinnamon:
        arch: [ cinnamon, lightdm-gtk-greeter, cosmic-store, firefox, gnome-terminal ]
        debian: [ task-cinnamon-desktop, lightdm-gtk-greeter ]
        fedora: [ "@Cinnamon Desktop", lightdm-gtk-greeter ]
    LXQT-Desktop:
        arch: [ xorg, lxqt, breeze-icons, oxygen-icons, sddm, network-manager-applet, firefox, cosmic-store, leafpad, vlc ]
        debian: [ task-lxqt-desktop, sddm ]
        fedora: [ "@LXQt Desktop", sddm ]
    MATE-Desktop:
        arch: [ mate, mate-extra, firefox, lightdm-gtk-greeter, cosmic-store, vlc ]
        debian: [ task-mate-desktop, lightdm-gtk-greeter ]
        fedora: [ "@MATE Desktop", lightdm-gtk-greeter ]
    Cosmic:
        arch: [ cosmic, firefox, vlc ]
        debian: [ cosmic, firefox, vlc ]
        fedora: [ cosmic, firefox, vlc ]
