# SPDX-FileCopyrightText: no
# SPDX-License-Identifier: CC0-1.0
#
# Arch only: re-enable running 90-mkinitcpio-install.hook for installed system
# Debian uses initramfs-tools, Fedora uses dracut - no equivalent needed
---

dontChroot: false

script:
 - 'if [ "$DISTRO" = "arch" ]; then rm /etc/pacman.d/hooks/90-mkinitcpio-install.hook; fi'
 - 'if [ "$DISTRO" = "arch" ]; then rm /usr/share/libalpm/scripts/mkinitcpio-install-calamares; fi'

i18n:
 name: "reset 90-mkinitcpio-install.hook (arch only)"
